//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocFolders.BulkLoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public string Content { get; set; }
        public System.Guid DocId { get; set; }
        public System.Guid FolderId { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual Folder Folder { get; set; }
    }
}
