//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocFolders.BulkLoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc()
        {
            this.Folders = new HashSet<Folder>();
            this.Comments = new HashSet<Comment>();
            this.MainDocs = new HashSet<Doc>();
            this.AttachedDocs = new HashSet<Doc>();
        }
    
        public System.Guid Id { get; set; }
        public string Caption { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateLoaded { get; set; }
        public string UserLoaded { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string UserChanged { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public Nullable<System.DateTime> DateFixed { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Folder> Folders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc> MainDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc> AttachedDocs { get; set; }
    }
}
